export const RESULTS_CONTRACT_FIXTURES = Object.freeze({
  legacyCandidate: {
    id: 'cand-legacy-1',
    name: 'Alex Rivera',
    email: 'alex@example.com',
    score: 88,
    skills: 'React, Node.js, TypeScript',
    profile_score: 88,
    years_experience: 6,
    seniority_level: 'senior',
    top_skills: ['React', 'Node.js', 'TypeScript'],
    fit_assessment: {
      overall_fit_score: 88,
      skill_match_score: 86,
      experience_match_score: 90,
    },
  },
  modernCandidate: {
    candidateId: 'cand-modern-1',
    resumeId: '550e8400-e29b-41d4-a716-446655440000',
    name: 'Alex Rivera',
    email: 'alex@example.com',
    score: 88,
    skills_structured: {
      tools_and_platforms: ['React', 'Node.js', 'TypeScript'],
      methodologies: ['Agile'],
      domain_expertise: ['SaaS'],
      soft_skills: ['Mentorship'],
    },
    skills_flat: ['React', 'Node.js', 'TypeScript'],
    profile_score: 88,
    years_experience: 6,
    seniority_level: 'senior',
    top_skills: ['React', 'Node.js', 'TypeScript'],
    fit_assessment: {
      overall_fit_score: 88,
      skill_match_score: 86,
      experience_match_score: 90,
    },
    matchScore: {
      score: 88,
      reason: 'Strong fit for role requirements',
    },
  },
})
