export const RESULTS_CONTRACT_FIXTURES = Object.freeze({
  legacyCandidate: {
    id: 'cand-legacy-1',
    name: 'Alex Rivera',
    email: 'alex@example.com',
    score: 88,
    skills: 'React, Node.js, TypeScript',
    profile_score: 88,
    years_experience: 6,
    seniority_level: 'senior',
    top_skills: ['React', 'Node.js', 'TypeScript'],
    fit_assessment: {
      overall_fit_score: 88,
      skill_match_score: 86,
      experience_match_score: 90,
    },
    matchScore: {
      score: 88,
      reason: 'Strong fit for role requirements',
    },
  },
  modernCandidate: {
    candidateId: 'cand-modern-1',
    resumeId: '550e8400-e29b-41d4-a716-446655440000',
    name: 'Alex Rivera',
    email: 'alex@example.com',
    score: 88,
    skills_structured: {
      tools_and_platforms: ['React', 'Node.js', 'TypeScript'],
      methodologies: ['Agile'],
      domain_expertise: ['SaaS'],
      soft_skills: ['Mentorship'],
    },
    skills_flat: ['React', 'Node.js', 'TypeScript'],
    profile_score: 88,
    years_experience: 6,
    seniority_level: 'senior',
    top_skills: ['React', 'Node.js', 'TypeScript'],
    fit_assessment: {
      overall_fit_score: 88,
      skill_match_score: 86,
      experience_match_score: 90,
    },
    matchScore: {
      score: 88,
      reason: 'Strong fit for role requirements',
    },
  },
  candidateV3OptIn: {
    candidateId: 'cand-v3-1',
    resumeId: '550e8400-e29b-41d4-a716-446655440001',
    name: 'Jordan Lee',
    score: 81,
    matchedRequirements: ['Node.js API development', 'PostgreSQL query optimization'],
    missingRequirements: ['SOC2 operations ownership'],
    evidence: [
      { quote: 'Built Node.js microservices for customer APIs', section: 'Experience', span: 'Acme Corp, 2022-2025' },
    ],
    uncertaintyNotes: ['Limited evidence for compliance ownership'],
    suggestedRecruiterAction: 'Probe compliance depth in technical screen.',
    resumeFilename: 'jordan-lee-resume.pdf',
    resumeAssetRef: 'asset://resume/jordan-lee-1',
    parseMeta: { contractVersion: 'candidate-v3', contractMode: 'opt_in' },
  },
})
